### ISSUE TITLE
Not sure how to use tests.html

### ISSUE THREAD

**Issue by thegsi** [koalabears/koala-complete#47]

**Comment by mk4111** [comment]
It's supposed to be hidden and relatively inaccessible, so that the front-end qunit tests wouldn't show on the client-side web page --> employed the 'iframe' method that Rafe and Nelson explained to everyone a few days back, so that we wouldn't need to copy and paste the entire index.html every time we wanted to test it.

test.html only shows if someone deliberately typed in: '/test.html/' after the heroku app default url, so it looks like:

```
https://shielded-dusk-6658.herokuapp.com/test.html/
```
